spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    config:
        activate:
            on-profile: create
logging:
    level:
        org.hibernate.type: trace
